Business Problem

      ↓
Data Collection

      ↓
Data Understanding

      ↓
Data Cleaning

      ↓
Exploratory Data Analysis (EDA)

      ↓
Feature Engineering

      ↓
Feature Selection

      ↓
Train/Test Split

      ↓
Model Training

      ↓
Model Evaluation

      ↓
Hyperparameter Tuning

      ↓
Model Testing


      ↓
Model Deployment

      ↓
Monitoring & Retraining

### Data collection methods
- SQL connectors (pymysql for mysql, pyodbc for mssql, psycopg2 for postgresql)
- API requests
- CSV, Excel, JSON, and XML data ingestion
- Data scraping with BeautifulSoup and selenium

In [2]:
# sample mysql connect code
import pymysql

connection = pymysql.connect(
    host="localhost",
    port=3306,
    user="root",
    password="@Aravind2004",
    database="world"
)

print("Connected Successfully!")

Connected Successfully!

In [3]:
cursor = connection.cursor()

cursor.execute("SELECT * FROM country")
for row in cursor.fetchall():
    
    print(row)
    
cursor.close()

('ABW', 'Aruba', 'North America', 'Caribbean', Decimal('193.00'), None, 103000, Decimal('78.4'), Decimal('828.00'), Decimal('793.00'), 'Aruba', 'Nonmetropolitan Territory of The Netherlands', 'Beatrix', 129, 'AW')
('AFG', 'Afghanistan', 'Asia', 'Southern and Central Asia', Decimal('652090.00'), 1919, 22720000, Decimal('45.9'), Decimal('5976.00'), None, 'Afganistan/Afqanestan', 'Islamic Emirate', 'Mohammad Omar', 1, 'AF')
('AGO', 'Angola', 'Africa', 'Central Africa', Decimal('1246700.00'), 1975, 12878000, Decimal('38.3'), Decimal('6648.00'), Decimal('7984.00'), 'Angola', 'Republic', 'José Eduardo dos Santos', 56, 'AO')
('AIA', 'Anguilla', 'North America', 'Caribbean', Decimal('96.00'), None, 8000, Decimal('76.1'), Decimal('63.20'), None, 'Anguilla', 'Dependent Territory of the UK', 'Elisabeth II', 62, 'AI')
('ALB', 'Albania', 'Europe', 'Southern Europe', Decimal('28748.00'), 1912, 3401200, Decimal('71.6'), Decimal('3205.00'), Decimal('2500.00'), 'Shqipëria', 'Republic', 'Rexhep Mejdani', 34, 'AL')
('AND', 'Andorra', 'Europe', 'Southern Europe', Decimal('468.00'), 1278, 78000, Decimal('83.5'), Decimal('1630.00'), None, 'Andorra', 'Parliamentary Coprincipality', '', 55, 'AD')
('ANT', 'Netherlands Antilles', 'North America', 'Caribbean', Decimal('800.00'), None, 217000, Decimal('74.7'), Decimal('1941.00'), None, 'Nederlandse Antillen', 'Nonmetropolitan Territory of The Netherlands', 'Beatrix', 33, 'AN')
('ARE', 'United Arab Emirates', 'Asia', 'Middle East', Decimal('83600.00'), 1971, 2441000, Decimal('74.1'), Decimal('37966.00'), Decimal('36846.00'), 'Al-Imarat al-´Arabiya al-Muttahida', 'Emirate Federation', 'Zayid bin Sultan al-Nahayan', 65, 'AE')
('ARG', 'Argentina', 'South America', 'South America', Decimal('2780400.00'), 1816, 37032000, Decimal('75.1'), Decimal('340238.00'), Decimal('323310.00'), 'Argentina', 'Federal Republic', 'Fernando de la Rúa', 69, 'AR')
('ARM', 'Armenia', 'Asia', 'Middle East', Decimal('29800.00'), 1991, 3520000, Decimal('66.4'), Decimal('1813.00'), Decimal('1627.00'), 'Hajastan', 'Republic', 'Robert Kotšarjan', 126, 'AM')
('ASM', 'American Samoa', 'Oceania', 'Polynesia', Decimal('199.00'), None, 68000, Decimal('75.1'), Decimal('334.00'), None, 'Amerika Samoa', 'US Territory', 'George W. Bush', 54, 'AS')
('ATA', 'Antarctica', 'Antarctica', 'Antarctica', Decimal('13120000.00'), None, 0, None, Decimal('0.00'), None, '–', 'Co-administrated', '', None, 'AQ')
('ATF', 'French Southern territories', 'Antarctica', 'Antarctica', Decimal('7780.00'), None, 0, None, Decimal('0.00'), None, 'Terres australes françaises', 'Nonmetropolitan Territory of France', 'Jacques Chirac', None, 'TF')
('ATG', 'Antigua and Barbuda', 'North America', 'Caribbean', Decimal('442.00'), 1981, 68000, Decimal('70.5'), Decimal('612.00'), Decimal('584.00'), 'Antigua and Barbuda', 'Constitutional Monarchy', 'Elisabeth II', 63, 'AG')
('AUS', 'Australia', 'Oceania', 'Australia and New Zealand', Decimal('7741220.00'), 1901, 18886000, Decimal('79.8'), Decimal('351182.00'), Decimal('392911.00'), 'Australia', 'Constitutional Monarchy, Federation', 'Elisabeth II', 135, 'AU')
('AUT', 'Austria', 'Europe', 'Western Europe', Decimal('83859.00'), 1918, 8091800, Decimal('77.7'), Decimal('211860.00'), Decimal('206025.00'), 'Österreich', 'Federal Republic', 'Thomas Klestil', 1523, 'AT')
('AZE', 'Azerbaijan', 'Asia', 'Middle East', Decimal('86600.00'), 1991, 7734000, Decimal('62.9'), Decimal('4127.00'), Decimal('4100.00'), 'Azärbaycan', 'Federal Republic', 'Heydär Äliyev', 144, 'AZ')
('BDI', 'Burundi', 'Africa', 'Eastern Africa', Decimal('27834.00'), 1962, 6695000, Decimal('46.2'), Decimal('903.00'), Decimal('982.00'), 'Burundi/Uburundi', 'Republic', 'Pierre Buyoya', 552, 'BI')
('BEL', 'Belgium', 'Europe', 'Western Europe', Decimal('30518.00'), 1830, 10239000, Decimal('77.8'), Decimal('249704.00'), Decimal('243948.00'), 'België/Belgique', 'Constitutional Monarchy, Federation', 'Albert II', 179, 'BE')
('BEN', 'Benin', 'Africa', 'Western Africa', Decimal('112622.00'), 1960, 6097000, Decimal('50.2'), Decimal('2357.00'), Decimal('2141.00'), 'Bénin', 'Republic', 'Mathieu Kérékou', 187, 'BJ')
('BFA', 'Burkina Faso', 'Africa', 'Western Africa', Decimal('274000.00'), 1960, 11937000, Decimal('46.7'), Decimal('2425.00'), Decimal('2201.00'), 'Burkina Faso', 'Republic', 'Blaise Compaoré', 549, 'BF')
('BGD', 'Bangladesh', 'Asia', 'Southern and Central Asia', Decimal('143998.00'), 1971, 129155000, Decimal('60.2'), Decimal('32852.00'), Decimal('31966.00'), 'Bangladesh', 'Republic', 'Shahabuddin Ahmad', 150, 'BD')
('BGR', 'Bulgaria', 'Europe', 'Eastern Europe', Decimal('110994.00'), 1908, 8190900, Decimal('70.9'), Decimal('12178.00'), Decimal('10169.00'), 'Balgarija', 'Republic', 'Petar Stojanov', 539, 'BG')
('BHR', 'Bahrain', 'Asia', 'Middle East', Decimal('694.00'), 1971, 617000, Decimal('73.0'), Decimal('6366.00'), Decimal('6097.00'), 'Al-Bahrayn', 'Monarchy (Emirate)', 'Hamad ibn Isa al-Khalifa', 149, 'BH')
('BHS', 'Bahamas', 'North America', 'Caribbean', Decimal('13878.00'), 1973, 307000, Decimal('71.1'), Decimal('3527.00'), Decimal('3347.00'), 'The Bahamas', 'Constitutional Monarchy', 'Elisabeth II', 148, 'BS')
('BIH', 'Bosnia and Herzegovina', 'Europe', 'Southern Europe', Decimal('51197.00'), 1992, 3972000, Decimal('71.5'), Decimal('2841.00'), None, 'Bosna i Hercegovina', 'Federal Republic', 'Ante Jelavic', 201, 'BA')
('BLR', 'Belarus', 'Europe', 'Eastern Europe', Decimal('207600.00'), 1991, 10236000, Decimal('68.0'), Decimal('13714.00'), None, 'Belarus', 'Republic', 'Aljaksandr Lukašenka', 3520, 'BY')
('BLZ', 'Belize', 'North America', 'Central America', Decimal('22696.00'), 1981, 241000, Decimal('70.9'), Decimal('630.00'), Decimal('616.00'), 'Belize', 'Constitutional Monarchy', 'Elisabeth II', 185, 'BZ')
('BMU', 'Bermuda', 'North America', 'North America', Decimal('53.00'), None, 65000, Decimal('76.9'), Decimal('2328.00'), Decimal('2190.00'), 'Bermuda', 'Dependent Territory of the UK', 'Elisabeth II', 191, 'BM')
('BOL', 'Bolivia', 'South America', 'South America', Decimal('1098581.00'), 1825, 8329000, Decimal('63.7'), Decimal('8571.00'), Decimal('7967.00'), 'Bolivia', 'Republic', 'Hugo Bánzer Suárez', 194, 'BO')
('BRA', 'Brazil', 'South America', 'South America', Decimal('8547403.00'), 1822, 170115000, Decimal('62.9'), Decimal('776739.00'), Decimal('804108.00'), 'Brasil', 'Federal Republic', 'Fernando Henrique Cardoso', 211, 'BR')
('BRB', 'Barbados', 'North America', 'Caribbean', Decimal('430.00'), 1966, 270000, Decimal('73.0'), Decimal('2223.00'), Decimal('2186.00'), 'Barbados', 'Constitutional Monarchy', 'Elisabeth II', 174, 'BB')
('BRN', 'Brunei', 'Asia', 'Southeast Asia', Decimal('5765.00'), 1984, 328000, Decimal('73.6'), Decimal('11705.00'), Decimal('12460.00'), 'Brunei Darussalam', 'Monarchy (Sultanate)', 'Haji Hassan al-Bolkiah', 538, 'BN')
('BTN', 'Bhutan', 'Asia', 'Southern and Central Asia', Decimal('47000.00'), 1910, 2124000, Decimal('52.4'), Decimal('372.00'), Decimal('383.00'), 'Druk-Yul', 'Monarchy', 'Jigme Singye Wangchuk', 192, 'BT')
('BVT', 'Bouvet Island', 'Antarctica', 'Antarctica', Decimal('59.00'), None, 0, None, Decimal('0.00'), None, 'Bouvetøya', 'Dependent Territory of Norway', 'Harald V', None, 'BV')
('BWA', 'Botswana', 'Africa', 'Southern Africa', Decimal('581730.00'), 1966, 1622000, Decimal('39.3'), Decimal('4834.00'), Decimal('4935.00'), 'Botswana', 'Republic', 'Festus G. Mogae', 204, 'BW')
('CAF', 'Central African Republic', 'Africa', 'Central Africa', Decimal('622984.00'), 1960, 3615000, Decimal('44.0'), Decimal('1054.00'), Decimal('993.00'), 'Centrafrique/Bê-Afrîka', 'Republic', 'Ange-Félix Patassé', 1889, 'CF')
('CAN', 'Canada', 'North America', 'North America', Decimal('9970610.00'), 1867, 31147000, Decimal('79.4'), Decimal('598862.00'), Decimal('625626.00'), 'Canada', 'Constitutional Monarchy, Federation', 'Elisabeth II', 1822, 'CA')
('CCK', 'Cocos (Keeling) Islands', 'Oceania', 'Australia and New Zealand', Decimal('14.00'), None, 600, None, Decimal('0.00'), None, 'Cocos (Keeling) Islands', 'Territory of Australia', 'Elisabeth II', 2317, 'CC')
('CHE', 'Switzerland', 'Europe', 'Western Europe', Decimal('41284.00'), 1499, 7160400, Decimal('79.6'), Decimal('264478.00'), Decimal('256092.00'), 'Schweiz/Suisse/Svizzera/Svizra', 'Federation', 'Adolf Ogi', 3248, 'CH')
('CHL', 'Chile', 'South America', 'South America', Decimal('756626.00'), 1810, 15211000, Decimal('75.7'), Decimal('72949.00'), Decimal('75780.00'), 'Chile', 'Republic', 'Ricardo Lagos Escobar', 554, 'CL')
('CHN', 'China', 'Asia', 'Eastern Asia', Decimal('9572900.00'), -1523, 1277558000, Decimal('71.4'), Decimal('982268.00'), Decimal('917719.00'), 'Zhongquo', "People'sRepublic", 'Jiang Zemin', 1891, 'CN')
('CIV', 'Côte d’Ivoire', 'Africa', 'Western Africa', Decimal('322463.00'), 1960, 14786000, Decimal('45.2'), Decimal('11345.00'), Decimal('10285.00'), 'Côte d’Ivoire', 'Republic', 'Laurent Gbagbo', 2814, 'CI')
('CMR', 'Cameroon', 'Africa', 'Central Africa', Decimal('475442.00'), 1960, 15085000, Decimal('54.8'), Decimal('9174.00'), Decimal('8596.00'), 'Cameroun/Cameroon', 'Republic', 'Paul Biya', 1804, 'CM')
('COD', 'Congo, The Democratic Republic of the', 'Africa', 'Central Africa', Decimal('2344858.00'), 1960, 51654000, Decimal('48.8'), Decimal('6964.00'), Decimal('2474.00'), 'République Démocratique du Congo', 'Republic', 'Joseph Kabila', 2298, 'CD')
('COG', 'Congo', 'Africa', 'Central Africa', Decimal('342000.00'), 1960, 2943000, Decimal('47.4'), Decimal('2108.00'), Decimal('2287.00'), 'Congo', 'Republic', 'Denis Sassou-Nguesso', 2296, 'CG')
('COK', 'Cook Islands', 'Oceania', 'Polynesia', Decimal('236.00'), None, 20000, Decimal('71.1'), Decimal('100.00'), None, 'The Cook Islands', 'Nonmetropolitan Territory of New Zealand', 'Elisabeth II', 583, 'CK')
('COL', 'Colombia', 'South America', 'South America', Decimal('1138914.00'), 1810, 42321000, Decimal('70.3'), Decimal('102896.00'), Decimal('105116.00'), 'Colombia', 'Republic', 'Andrés Pastrana Arango', 2257, 'CO')
('COM', 'Comoros', 'Africa', 'Eastern Africa', Decimal('1862.00'), 1975, 578000, Decimal('60.0'), Decimal('4401.00'), Decimal('4361.00'), 'Komori/Comores', 'Republic', 'Azali Assoumani', 2295, 'KM')
('CPV', 'Cape Verde', 'Africa', 'Western Africa', Decimal('4033.00'), 1975, 428000, Decimal('68.9'), Decimal('435.00'), Decimal('420.00'), 'Cabo Verde', 'Republic', 'António Mascarenhas Monteiro', 1859, 'CV')
('CRI', 'Costa Rica', 'North America', 'Central America', Decimal('51100.00'), 1821, 4023000, Decimal('75.8'), Decimal('10226.00'), Decimal('9757.00'), 'Costa Rica', 'Republic', 'Miguel Ángel Rodríguez Echeverría', 584, 'CR')
('CUB', 'Cuba', 'North America', 'Caribbean', Decimal('110861.00'), 1902, 11201000, Decimal('76.2'), Decimal('17843.00'), Decimal('18862.00'), 'Cuba', 'Socialistic Republic', 'Fidel Castro Ruz', 2413, 'CU')
('CXR', 'Christmas Island', 'Oceania', 'Australia and New Zealand', Decimal('135.00'), None, 2500, None, Decimal('0.00'), None, 'Christmas Island', 'Territory of Australia', 'Elisabeth II', 1791, 'CX')
('CYM', 'Cayman Islands', 'North America', 'Caribbean', Decimal('264.00'), None, 38000, Decimal('78.9'), Decimal('1263.00'), Decimal('1186.00'), 'Cayman Islands', 'Dependent Territory of the UK', 'Elisabeth II', 553, 'KY')
('CYP', 'Cyprus', 'Asia', 'Middle East', Decimal('9251.00'), 1960, 754700, Decimal('76.7'), Decimal('9333.00'), Decimal('8246.00'), 'Kýpros/Kibris', 'Republic', 'Glafkos Klerides', 2430, 'CY')
('CZE', 'Czech Republic', 'Europe', 'Eastern Europe', Decimal('78866.00'), 1993, 10278100, Decimal('74.5'), Decimal('55017.00'), Decimal('52037.00'), '¸esko', 'Republic', 'Václav Havel', 3339, 'CZ')
('DEU', 'Germany', 'Europe', 'Western Europe', Decimal('357022.00'), 1955, 82164700, Decimal('77.4'), Decimal('2133367.00'), Decimal('2102826.00'), 'Deutschland', 'Federal Republic', 'Johannes Rau', 3068, 'DE')
('DJI', 'Djibouti', 'Africa', 'Eastern Africa', Decimal('23200.00'), 1977, 638000, Decimal('50.8'), Decimal('382.00'), Decimal('373.00'), 'Djibouti/Jibuti', 'Republic', 'Ismail Omar Guelleh', 585, 'DJ')
('DMA', 'Dominica', 'North America', 'Caribbean', Decimal('751.00'), 1978, 71000, Decimal('73.4'), Decimal('256.00'), Decimal('243.00'), 'Dominica', 'Republic', 'Vernon Shaw', 586, 'DM')
('DNK', 'Denmark', 'Europe', 'Nordic Countries', Decimal('43094.00'), 800, 5330000, Decimal('76.5'), Decimal('174099.00'), Decimal('169264.00'), 'Danmark', 'Constitutional Monarchy', 'Margrethe II', 3315, 'DK')
('DOM', 'Dominican Republic', 'North America', 'Caribbean', Decimal('48511.00'), 1844, 8495000, Decimal('73.2'), Decimal('15846.00'), Decimal('15076.00'), 'República Dominicana', 'Republic', 'Hipólito Mejía Domínguez', 587, 'DO')
('DZA', 'Algeria', 'Africa', 'Northern Africa', Decimal('2381741.00'), 1962, 31471000, Decimal('69.7'), Decimal('49982.00'), Decimal('46966.00'), 'Al-Jaza’ir/Algérie', 'Republic', 'Abdelaziz Bouteflika', 35, 'DZ')
('ECU', 'Ecuador', 'South America', 'South America', Decimal('283561.00'), 1822, 12646000, Decimal('71.1'), Decimal('19770.00'), Decimal('19769.00'), 'Ecuador', 'Republic', 'Gustavo Noboa Bejarano', 594, 'EC')
('EGY', 'Egypt', 'Africa', 'Northern Africa', Decimal('1001449.00'), 1922, 68470000, Decimal('63.3'), Decimal('82710.00'), Decimal('75617.00'), 'Misr', 'Republic', 'Hosni Mubarak', 608, 'EG')
('ERI', 'Eritrea', 'Africa', 'Eastern Africa', Decimal('117600.00'), 1993, 3850000, Decimal('55.8'), Decimal('650.00'), Decimal('755.00'), 'Ertra', 'Republic', 'Isayas Afewerki [Isaias Afwerki]', 652, 'ER')
('ESH', 'Western Sahara', 'Africa', 'Northern Africa', Decimal('266000.00'), None, 293000, Decimal('49.8'), Decimal('60.00'), None, 'As-Sahrawiya', 'Occupied by Marocco', 'Mohammed Abdel Aziz', 2453, 'EH')
('ESP', 'Spain', 'Europe', 'Southern Europe', Decimal('505992.00'), 1492, 39441700, Decimal('78.8'), Decimal('553233.00'), Decimal('532031.00'), 'España', 'Constitutional Monarchy', 'Juan Carlos I', 653, 'ES')
('EST', 'Estonia', 'Europe', 'Baltic Countries', Decimal('45227.00'), 1991, 1439200, Decimal('69.5'), Decimal('5328.00'), Decimal('3371.00'), 'Eesti', 'Republic', 'Lennart Meri', 3791, 'EE')
('ETH', 'Ethiopia', 'Africa', 'Eastern Africa', Decimal('1104300.00'), -1000, 62565000, Decimal('45.2'), Decimal('6353.00'), Decimal('6180.00'), 'YeItyop´iya', 'Republic', 'Negasso Gidada', 756, 'ET')
('FIN', 'Finland', 'Europe', 'Nordic Countries', Decimal('338145.00'), 1917, 5171300, Decimal('77.4'), Decimal('121914.00'), Decimal('119833.00'), 'Suomi', 'Republic', 'Tarja Halonen', 3236, 'FI')
('FJI', 'Fiji Islands', 'Oceania', 'Melanesia', Decimal('18274.00'), 1970, 817000, Decimal('67.9'), Decimal('1536.00'), Decimal('2149.00'), 'Fiji Islands', 'Republic', 'Josefa Iloilo', 764, 'FJ')
('FLK', 'Falkland Islands', 'South America', 'South America', Decimal('12173.00'), None, 2000, None, Decimal('0.00'), None, 'Falkland Islands', 'Dependent Territory of the UK', 'Elisabeth II', 763, 'FK')
('FRA', 'France', 'Europe', 'Western Europe', Decimal('551500.00'), 843, 59225700, Decimal('78.8'), Decimal('1424285.00'), Decimal('1392448.00'), 'France', 'Republic', 'Jacques Chirac', 2974, 'FR')
('FRO', 'Faroe Islands', 'Europe', 'Nordic Countries', Decimal('1399.00'), None, 43000, Decimal('78.4'), Decimal('0.00'), None, 'Føroyar', 'Part of Denmark', 'Margrethe II', 901, 'FO')
('FSM', 'Micronesia, Federated States of', 'Oceania', 'Micronesia', Decimal('702.00'), 1990, 119000, Decimal('68.6'), Decimal('212.00'), None, 'Micronesia', 'Federal Republic', 'Leo A. Falcam', 2689, 'FM')
('GAB', 'Gabon', 'Africa', 'Central Africa', Decimal('267668.00'), 1960, 1226000, Decimal('50.1'), Decimal('5493.00'), Decimal('5279.00'), 'Le Gabon', 'Republic', 'Omar Bongo', 902, 'GA')
('GBR', 'United Kingdom', 'Europe', 'British Islands', Decimal('242900.00'), 1066, 59623400, Decimal('77.7'), Decimal('1378330.00'), Decimal('1296830.00'), 'United Kingdom', 'Constitutional Monarchy', 'Elisabeth II', 456, 'GB')
('GEO', 'Georgia', 'Asia', 'Middle East', Decimal('69700.00'), 1991, 4968000, Decimal('64.5'), Decimal('6064.00'), Decimal('5924.00'), 'Sakartvelo', 'Republic', 'Eduard Ševardnadze', 905, 'GE')
('GHA', 'Ghana', 'Africa', 'Western Africa', Decimal('238533.00'), 1957, 20212000, Decimal('57.4'), Decimal('7137.00'), Decimal('6884.00'), 'Ghana', 'Republic', 'John Kufuor', 910, 'GH')
('GIB', 'Gibraltar', 'Europe', 'Southern Europe', Decimal('6.00'), None, 25000, Decimal('79.0'), Decimal('258.00'), None, 'Gibraltar', 'Dependent Territory of the UK', 'Elisabeth II', 915, 'GI')
('GIN', 'Guinea', 'Africa', 'Western Africa', Decimal('245857.00'), 1958, 7430000, Decimal('45.6'), Decimal('2352.00'), Decimal('2383.00'), 'Guinée', 'Republic', 'Lansana Conté', 926, 'GN')
('GLP', 'Guadeloupe', 'North America', 'Caribbean', Decimal('1705.00'), None, 456000, Decimal('77.0'), Decimal('3501.00'), None, 'Guadeloupe', 'Overseas Department of France', 'Jacques Chirac', 919, 'GP')
('GMB', 'Gambia', 'Africa', 'Western Africa', Decimal('11295.00'), 1965, 1305000, Decimal('53.2'), Decimal('320.00'), Decimal('325.00'), 'The Gambia', 'Republic', 'Yahya Jammeh', 904, 'GM')
('GNB', 'Guinea-Bissau', 'Africa', 'Western Africa', Decimal('36125.00'), 1974, 1213000, Decimal('49.0'), Decimal('293.00'), Decimal('272.00'), 'Guiné-Bissau', 'Republic', 'Kumba Ialá', 927, 'GW')
('GNQ', 'Equatorial Guinea', 'Africa', 'Central Africa', Decimal('28051.00'), 1968, 453000, Decimal('53.6'), Decimal('283.00'), Decimal('542.00'), 'Guinea Ecuatorial', 'Republic', 'Teodoro Obiang Nguema Mbasogo', 2972, 'GQ')
('GRC', 'Greece', 'Europe', 'Southern Europe', Decimal('131626.00'), 1830, 10545700, Decimal('78.4'), Decimal('120724.00'), Decimal('119946.00'), 'Elláda', 'Republic', 'Kostis Stefanopoulos', 2401, 'GR')
('GRD', 'Grenada', 'North America', 'Caribbean', Decimal('344.00'), 1974, 94000, Decimal('64.5'), Decimal('318.00'), None, 'Grenada', 'Constitutional Monarchy', 'Elisabeth II', 916, 'GD')
('GRL', 'Greenland', 'North America', 'North America', Decimal('2166090.00'), None, 56000, Decimal('68.1'), Decimal('0.00'), None, 'Kalaallit Nunaat/Grønland', 'Part of Denmark', 'Margrethe II', 917, 'GL')
('GTM', 'Guatemala', 'North America', 'Central America', Decimal('108889.00'), 1821, 11385000, Decimal('66.2'), Decimal('19008.00'), Decimal('17797.00'), 'Guatemala', 'Republic', 'Alfonso Portillo Cabrera', 922, 'GT')
('GUF', 'French Guiana', 'South America', 'South America', Decimal('90000.00'), None, 181000, Decimal('76.1'), Decimal('681.00'), None, 'Guyane française', 'Overseas Department of France', 'Jacques Chirac', 3014, 'GF')
('GUM', 'Guam', 'Oceania', 'Micronesia', Decimal('549.00'), None, 168000, Decimal('77.8'), Decimal('1197.00'), Decimal('1136.00'), 'Guam', 'US Territory', 'George W. Bush', 921, 'GU')
('GUY', 'Guyana', 'South America', 'South America', Decimal('214969.00'), 1966, 861000, Decimal('64.0'), Decimal('722.00'), Decimal('743.00'), 'Guyana', 'Republic', 'Bharrat Jagdeo', 928, 'GY')
('HKG', 'Hong Kong', 'Asia', 'Eastern Asia', Decimal('1075.00'), None, 6782000, Decimal('79.5'), Decimal('166448.00'), Decimal('173610.00'), 'Xianggang/Hong Kong', 'Special Administrative Region of China', 'Jiang Zemin', 937, 'HK')
('HMD', 'Heard Island and McDonald Islands', 'Antarctica', 'Antarctica', Decimal('359.00'), None, 0, None, Decimal('0.00'), None, 'Heard and McDonald Islands', 'Territory of Australia', 'Elisabeth II', None, 'HM')
('HND', 'Honduras', 'North America', 'Central America', Decimal('112088.00'), 1838, 6485000, Decimal('69.9'), Decimal('5333.00'), Decimal('4697.00'), 'Honduras', 'Republic', 'Carlos Roberto Flores Facussé', 933, 'HN')
('HRV', 'Croatia', 'Europe', 'Southern Europe', Decimal('56538.00'), 1991, 4473000, Decimal('73.7'), Decimal('20208.00'), Decimal('19300.00'), 'Hrvatska', 'Republic', 'Štipe Mesic', 2409, 'HR')
('HTI', 'Haiti', 'North America', 'Caribbean', Decimal('27750.00'), 1804, 8222000, Decimal('49.2'), Decimal('3459.00'), Decimal('3107.00'), 'Haïti/Dayti', 'Republic', 'Jean-Bertrand Aristide', 929, 'HT')

In [4]:
# API requests
import requests

url = "https://jsonplaceholder.typicode.com/users"

response = requests.get(url)

print(response.status_code)
print(response.text)

200
[
  {
    "id": 1,
    "name": "Leanne Graham",
    "username": "Bret",
    "email": "Sincere@april.biz",
    "address": {
      "street": "Kulas Light",
      "suite": "Apt. 556",
      "city": "Gwenborough",
      "zipcode": "92998-3874",
      "geo": {
        "lat": "-37.3159",
        "lng": "81.1496"
      }
    },
    "phone": "1-770-736-8031 x56442",
    "website": "hildegard.org",
    "company": {
      "name": "Romaguera-Crona",
      "catchPhrase": "Multi-layered client-server neural-net",
      "bs": "harness real-time e-markets"
    }
  },
  {
    "id": 2,
    "name": "Ervin Howell",
    "username": "Antonette",
    "email": "Shanna@melissa.tv",
    "address": {
      "street": "Victor Plains",
      "suite": "Suite 879",
      "city": "Wisokyburgh",
      "zipcode": "90566-7771",
      "geo": {
        "lat": "-43.9509",
        "lng": "-34.4618"
      }
    },
    "phone": "010-692-6593 x09125",
    "website": "anastasia.net",
    "company": {
      "name": "Deckow-Crist",
      "catchPhrase": "Proactive didactic contingency",
      "bs": "synergize scalable supply-chains"
    }
  },
  {
    "id": 3,
    "name": "Clementine Bauch",
    "username": "Samantha",
    "email": "Nathan@yesenia.net",
    "address": {
      "street": "Douglas Extension",
      "suite": "Suite 847",
      "city": "McKenziehaven",
      "zipcode": "59590-4157",
      "geo": {
        "lat": "-68.6102",
        "lng": "-47.0653"
      }
    },
    "phone": "1-463-123-4447",
    "website": "ramiro.info",
    "company": {
      "name": "Romaguera-Jacobson",
      "catchPhrase": "Face to face bifurcated interface",
      "bs": "e-enable strategic applications"
    }
  },
  {
    "id": 4,
    "name": "Patricia Lebsack",
    "username": "Karianne",
    "email": "Julianne.OConner@kory.org",
    "address": {
      "street": "Hoeger Mall",
      "suite": "Apt. 692",
      "city": "South Elvis",
      "zipcode": "53919-4257",
      "geo": {
        "lat": "29.4572",
        "lng": "-164.2990"
      }
    },
    "phone": "493-170-9623 x156",
    "website": "kale.biz",
    "company": {
      "name": "Robel-Corkery",
      "catchPhrase": "Multi-tiered zero tolerance productivity",
      "bs": "transition cutting-edge web services"
    }
  },
  {
    "id": 5,
    "name": "Chelsey Dietrich",
    "username": "Kamren",
    "email": "Lucio_Hettinger@annie.ca",
    "address": {
      "street": "Skiles Walks",
      "suite": "Suite 351",
      "city": "Roscoeview",
      "zipcode": "33263",
      "geo": {
        "lat": "-31.8129",
        "lng": "62.5342"
      }
    },
    "phone": "(254)954-1289",
    "website": "demarco.info",
    "company": {
      "name": "Keebler LLC",
      "catchPhrase": "User-centric fault-tolerant solution",
      "bs": "revolutionize end-to-end systems"
    }
  },
  {
    "id": 6,
    "name": "Mrs. Dennis Schulist",
    "username": "Leopoldo_Corkery",
    "email": "Karley_Dach@jasper.info",
    "address": {
      "street": "Norberto Crossing",
      "suite": "Apt. 950",
      "city": "South Christy",
      "zipcode": "23505-1337",
      "geo": {
        "lat": "-71.4197",
        "lng": "71.7478"
      }
    },
    "phone": "1-477-935-8478 x6430",
    "website": "ola.org",
    "company": {
      "name": "Considine-Lockman",
      "catchPhrase": "Synchronised bottom-line interface",
      "bs": "e-enable innovative applications"
    }
  },
  {
    "id": 7,
    "name": "Kurtis Weissnat",
    "username": "Elwyn.Skiles",
    "email": "Telly.Hoeger@billy.biz",
    "address": {
      "street": "Rex Trail",
      "suite": "Suite 280",
      "city": "Howemouth",
      "zipcode": "58804-1099",
      "geo": {
        "lat": "24.8918",
        "lng": "21.8984"
      }
    },
    "phone": "210.067.6132",
    "website": "elvis.io",
    "company": {
      "name": "Johns Group",
      "catchPhrase": "Configurable multimedia task-force",
      "bs": "generate enterprise e-tailers"
    }
  },
  {
    "id": 8,
    "name": "Nicholas Runolfsdottir V",
    "username": "Maxime_Nienow",
    "email": "Sherwood@rosamond.me",
    "address": {
      "street": "Ellsworth Summit",
      "suite": "Suite 729",
      "city": "Aliyaview",
      "zipcode": "45169",
      "geo": {
        "lat": "-14.3990",
        "lng": "-120.7677"
      }
    },
    "phone": "586.493.6943 x140",
    "website": "jacynthe.com",
    "company": {
      "name": "Abernathy Group",
      "catchPhrase": "Implemented secondary concept",
      "bs": "e-enable extensible e-tailers"
    }
  },
  {
    "id": 9,
    "name": "Glenna Reichert",
    "username": "Delphine",
    "email": "Chaim_McDermott@dana.io",
    "address": {
      "street": "Dayna Park",
      "suite": "Suite 449",
      "city": "Bartholomebury",
      "zipcode": "76495-3109",
      "geo": {
        "lat": "24.6463",
        "lng": "-168.8889"
      }
    },
    "phone": "(775)976-6794 x41206",
    "website": "conrad.com",
    "company": {
      "name": "Yost and Sons",
      "catchPhrase": "Switchable contextually-based project",
      "bs": "aggregate real-time technologies"
    }
  },
  {
    "id": 10,
    "name": "Clementina DuBuque",
    "username": "Moriah.Stanton",
    "email": "Rey.Padberg@karina.biz",
    "address": {
      "street": "Kattie Turnpike",
      "suite": "Suite 198",
      "city": "Lebsackbury",
      "zipcode": "31428-2261",
      "geo": {
        "lat": "-38.2386",
        "lng": "57.2232"
      }
    },
    "phone": "024-648-3804",
    "website": "ambrose.net",
    "company": {
      "name": "Hoeger LLC",
      "catchPhrase": "Centralized empowering task-force",
      "bs": "target end-to-end models"
    }
  }
]

In [ ]:
import requests

url = "https://api.data.gov.in/resource/527f270a-8618-4855-ad0c-6bf90ae72808 "

headers = {
    "Authorization": "Bearer 579b464db66ec23bdd000001cdd3946e44ce4aad7209ff7b23ac571b"
}

response = requests.get(url, headers=headers)

print(response.status_code)

502

In [ ]:
# CSV, Excel, JSON, and XML data ingestion

import pandas as pd

df = pd.read_csv("file_name.csv")
df1 = pd.read_excel("file_name.xlsx")
df2 = pd.read_json("file_name.json")
df3 = pd.read_xml("file_name.xml")

In [10]:
import requests
from bs4 import BeautifulSoup

url = "https://beminimalist.co/"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, "lxml")

section = soup.find("div", class_="product-item")

if section:
    print(section.prettify())
else:
    print("No matching element found.")

<div class="product-item" data-js-product-item="" id="product-item-6776323014817">
 <a class="product-item__image" data-js-product-item-image="" href="/collections/best-sellers/products/salicylic-lha-2-cleanser" style="padding-top:149.9999250000375%">
  <css-slider class="product-item__slider css-slider--no-desktop-drag css-slider--overlay-navigation" data-options='{
        "selector": ".product-item__image-figure",
        "navigationDOM": "&lt;span class=\"css-slider-button css-slider-prev\" style=\"display:none\"&gt; &lt;svg fill=\"none\" height=\"11\" viewBox=\"0 0 6 11\" width=\"6\" xmlns=\"http://www.w3.org/2000/svg\"&gt;&lt;g fill=\"#000\"&gt;&lt;path d=\"m5.82422 1.08691-4.949749 4.94975-.702717-.70272 4.949746-4.949743z\"/&gt;&lt;path d=\"m5.12158 10.2832-4.949745-4.94974.707107-.70711 4.949748 4.94975z\"/&gt;&lt;/g&gt;&lt;/svg&gt;&lt;/span&gt;&lt;span class=\"css-slider-button css-slider-next\" style=\"display:none\"&gt; &lt;svg fill=\"none\" height=\"11\" viewBox=\"0 0 6 11\" width=\"6\" xmlns=\"http://www.w3.org/2000/svg\" style=\"transform:rotate(180deg)\"&gt;&lt;g fill=\"#000\"&gt;&lt;path d=\"m5.82422 1.08691-4.949749 4.94975-.702717-.70272 4.949746-4.949743z\"/&gt;&lt;path d=\"m5.12158 10.2832-4.949745-4.94974.707107-.70711 4.949748 4.94975z\"/&gt;&lt;/g&gt;&lt;/svg&gt;&lt;/span&gt;",
        "disableSwipe": true
        }'>
   <div class="grid grid--slider grid-1 grid--gap-none">
    <figure class="lazy-image product-item__image-figure product-item__image-figure--top lazy-image--zoom-animation product-item__image-39642975502497 lazy-image--to-reveal" data-crop="false" data-ratio="0.666667" style="padding-top: 149.9999250000375%">
     <img alt="Salicylic Acid + LHA 2% Cleanser" class="img" data-ratio="0.666667" height="1600" sizes="(max-width: 359px) calc(100vw - 30px), (max-width: 767px) calc((100vw - 50px) / 2),(max-width: 1023px) calc((100vw - 100px) / 3), (max-width: 1360px) calc((100vw - 120px) / 4), 310px" src="https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/https://beminimalist.co/cdn/shop/files/SalicylicCleanserNew.jpg?v=1756796206&amp;width=480" srcset="https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/SalicylicCleanserNew.jpg?crop=center&amp;height=360&amp;v=1756796206&amp;width=240 240w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/SalicylicCleanserNew.jpg?crop=center&amp;height=540&amp;v=1756796206&amp;width=360 360w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/SalicylicCleanserNew.jpg?crop=center&amp;height=630&amp;v=1756796206&amp;width=420 420w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/SalicylicCleanserNew.jpg?crop=center&amp;height=720&amp;v=1756796206&amp;width=480 480w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/SalicylicCleanserNew.jpg?crop=center&amp;height=960&amp;v=1756796206&amp;width=640 640w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/SalicylicCleanserNew.jpg?crop=center&amp;height=1260&amp;v=1756796206&amp;width=840 840w" width="1100"/>
    </figure>
    <figure class="lazy-image product-item__image-figure product-item__image-figure--top lazy-image--zoom-animation product-item__image-39926817030305" data-crop="false" data-ratio="0.666667" style="padding-top: 149.9999250000375%">
     <img alt="Salicylic Acid + LHA 2% Cleanser" class="img" data-ratio="0.666667" height="1600" sizes="(max-width: 359px) calc(100vw - 30px), (max-width: 767px) calc((100vw - 50px) / 2),(max-width: 1023px) calc((100vw - 100px) / 3), (max-width: 1360px) calc((100vw - 120px) / 4), 310px" src="https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/https://beminimalist.co/cdn/shop/files/Salicylic_Cleanser_2.png?v=1724763872&amp;width=480" srcset="https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_2.png?crop=center&amp;height=360&amp;v=1724763872&amp;width=240 240w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_2.png?crop=center&amp;height=540&amp;v=1724763872&amp;width=360 360w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_2.png?crop=center&amp;height=630&amp;v=1724763872&amp;width=420 420w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_2.png?crop=center&amp;height=720&amp;v=1724763872&amp;width=480 480w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_2.png?crop=center&amp;height=960&amp;v=1724763872&amp;width=640 640w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_2.png?crop=center&amp;height=1260&amp;v=1724763872&amp;width=840 840w" width="1100"/>
    </figure>
    <figure class="lazy-image product-item__image-figure product-item__image-figure--top lazy-image--zoom-animation product-item__image-39926817063073" data-crop="false" data-ratio="0.666667" style="padding-top: 149.9999250000375%">
     <img alt="Salicylic Acid + LHA 2% Cleanser" class="img" data-ratio="0.666667" height="1600" sizes="(max-width: 359px) calc(100vw - 30px), (max-width: 767px) calc((100vw - 50px) / 2),(max-width: 1023px) calc((100vw - 100px) / 3), (max-width: 1360px) calc((100vw - 120px) / 4), 310px" src="https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/https://beminimalist.co/cdn/shop/files/Salicylic_Cleanser_3.png?v=1724763872&amp;width=480" srcset="https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_3.png?crop=center&amp;height=360&amp;v=1724763872&amp;width=240 240w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_3.png?crop=center&amp;height=540&amp;v=1724763872&amp;width=360 360w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_3.png?crop=center&amp;height=630&amp;v=1724763872&amp;width=420 420w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_3.png?crop=center&amp;height=720&amp;v=1724763872&amp;width=480 480w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_3.png?crop=center&amp;height=960&amp;v=1724763872&amp;width=640 640w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_3.png?crop=center&amp;height=1260&amp;v=1724763872&amp;width=840 840w" width="1100"/>
    </figure>
    <figure class="lazy-image product-item__image-figure product-item__image-figure--top lazy-image--zoom-animation product-item__image-39926817095841" data-crop="false" data-ratio="0.666667" style="padding-top: 149.9999250000375%">
     <img alt="Salicylic Acid + LHA 2% Cleanser" class="img" data-ratio="0.666667" height="1600" sizes="(max-width: 359px) calc(100vw - 30px), (max-width: 767px) calc((100vw - 50px) / 2),(max-width: 1023px) calc((100vw - 100px) / 3), (max-width: 1360px) calc((100vw - 120px) / 4), 310px" src="https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/https://beminimalist.co/cdn/shop/files/Salicylic_Cleanser_4.png?v=1724763872&amp;width=480" srcset="https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_4.png?crop=center&amp;height=360&amp;v=1724763872&amp;width=240 240w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_4.png?crop=center&amp;height=540&amp;v=1724763872&amp;width=360 360w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_4.png?crop=center&amp;height=630&amp;v=1724763872&amp;width=420 420w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_4.png?crop=center&amp;height=720&amp;v=1724763872&amp;width=480 480w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_4.png?crop=center&amp;height=960&amp;v=1724763872&amp;width=640 640w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_4.png?crop=center&amp;height=1260&amp;v=1724763872&amp;width=840 840w" width="1100"/>
    </figure>
    <figure class="lazy-image product-item__image-figure product-item__image-figure--top lazy-image--zoom-animation product-item__image-39926817128609" data-crop="false" data-ratio="0.666667" style="padding-top: 149.9999250000375%">
     <img alt="Salicylic Acid + LHA 2% Cleanser" class="img" data-ratio="0.666667" height="1600" sizes="(max-width: 359px) calc(100vw - 30px), (max-width: 767px) calc((100vw - 50px) / 2),(max-width: 1023px) calc((100vw - 100px) / 3), (max-width: 1360px) calc((100vw - 120px) / 4), 310px" src="https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/https://beminimalist.co/cdn/shop/files/Salicylic_Cleanser_5.png?v=1724763872&amp;width=480" srcset="https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_5.png?crop=center&amp;height=360&amp;v=1724763872&amp;width=240 240w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_5.png?crop=center&amp;height=540&amp;v=1724763872&amp;width=360 360w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_5.png?crop=center&amp;height=630&amp;v=1724763872&amp;width=420 420w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_5.png?crop=center&amp;height=720&amp;v=1724763872&amp;width=480 480w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_5.png?crop=center&amp;height=960&amp;v=1724763872&amp;width=640 640w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_5.png?crop=center&amp;height=1260&amp;v=1724763872&amp;width=840 840w" width="1100"/>
    </figure>
    <figure class="lazy-image product-item__image-figure product-item__image-figure--top lazy-image--zoom-animation product-item__image-39926817161377" data-crop="false" data-ratio="0.666667" style="padding-top: 149.9999250000375%">
     <img alt="Salicylic Acid + LHA 2% Cleanser" class="img" data-ratio="0.666667" height="1600" sizes="(max-width: 359px) calc(100vw - 30px), (max-width: 767px) calc((100vw - 50px) / 2),(max-width: 1023px) calc((100vw - 100px) / 3), (max-width: 1360px) calc((100vw - 120px) / 4), 310px" src="https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/https://beminimalist.co/cdn/shop/files/Salicylic_Cleanser_6.png?v=1724763871&amp;width=480" srcset="https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_6.png?crop=center&amp;height=360&amp;v=1724763871&amp;width=240 240w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_6.png?crop=center&amp;height=540&amp;v=1724763871&amp;width=360 360w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_6.png?crop=center&amp;height=630&amp;v=1724763871&amp;width=420 420w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_6.png?crop=center&amp;height=720&amp;v=1724763871&amp;width=480 480w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_6.png?crop=center&amp;height=960&amp;v=1724763871&amp;width=640 640w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/Salicylic_Cleanser_6.png?crop=center&amp;height=1260&amp;v=1724763871&amp;width=840 840w" width="1100"/>
    </figure>
    <figure class="lazy-image product-item__image-figure product-item__image-figure--top lazy-image--zoom-animation product-item__image-42258268094625" data-crop="false" data-ratio="0.666667" style="padding-top: 149.9999250000375%">
     <img alt="Salicylic Acid + LHA 2% Cleanser" class="img" data-ratio="0.666667" height="1600" sizes="(max-width: 359px) calc(100vw - 30px), (max-width: 767px) calc((100vw - 50px) / 2),(max-width: 1023px) calc((100vw - 100px) / 3), (max-width: 1360px) calc((100vw - 120px) / 4), 310px" src="https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/https://beminimalist.co/cdn/shop/files/SaliCleanser_ListingImage.png?v=1760691517&amp;width=480" srcset="https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/SaliCleanser_ListingImage.png?crop=center&amp;height=360&amp;v=1760691517&amp;width=240 240w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/SaliCleanser_ListingImage.png?crop=center&amp;height=540&amp;v=1760691517&amp;width=360 360w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/SaliCleanser_ListingImage.png?crop=center&amp;height=630&amp;v=1760691517&amp;width=420 420w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/SaliCleanser_ListingImage.png?crop=center&amp;height=720&amp;v=1760691517&amp;width=480 480w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/SaliCleanser_ListingImage.png?crop=center&amp;height=960&amp;v=1760691517&amp;width=640 640w,https://sfycdn.speedsize.com/56385b25-4e17-4a9a-9bec-c421c18686fb/beminimalist.co/cdn/shop/files/SaliCleanser_ListingImage.png?crop=center&amp;height=1260&amp;v=1760691517&amp;width=840 840w" width="1100"/>
    </figure>
   </div>
  </css-slider>
 </a>
 <div class="ctm_pdp_card_spacing card__text product-item__text gutter-top--regular gutter-bottom--regular spacing--xlarge remove-empty-space text-align--left" id="custom-product-card-spacing">
  <a class="product-item__title" href="/collections/best-sellers/products/salicylic-lha-2-cleanser" title="Salicylic Acid + LHA 2% Cleanser">
   <div class="remove-line-height-space--small">
    <span class="text-animation--underline-thin text-size--large text-weight--bold">
     Salicylic Acid + LHA 2% Cleanser
    </span>
   </div>
  </a>
  <div class="product-item__text text-size--small text-color--opacity text-line-height--medium equalize-white-space">
   <div class="remove-line-height-space--medium">
    Acne, Breakouts &amp; Oiliness
   </div>
  </div>
  <div class="product-item__ratings">
   <!-- Yotpo Star Rating(Category) | location: Snippets > product-item.liquid -->
   <!-- Snippets > yotpo-stars.liquid -->
   <div class="yotpo-widget-instance" data-yotpo-cart-product-id="" data-yotpo-instance-id="620237" data-yotpo-product-id="6776323014817" data-yotpo-section-id="index">
   </div>
   <!-- End | Snippets > yotpo-stars.liquid -->
   <!-- End of Yotpo Star Rating(Category) -->
  </div>
  <div class="product-item__price text-size--small equalize-white-space">
   <div class="remove-line-height-space" data-js-product-item-price="">
    <div class="product-price">
     <span class="product-price--original pps" data-js-product-price-original="">
      On Sale from ₹ 278
     </span>
     <del class="product-price--compare" data-js-product-price-compare="">
     </del>
     <span class="product-price--unit pps text-size--regular" data-js-product-price-unit="">
     </span>
    </div>
   </div>
  </div>
  <div class="product-item__icons">
  </div>
  <div class="product-item__quick-buy" data-id="quick_buy_wzzgtQ-template--18299834826913__featured_collection_new_RkNkxr-1">
   <quick-buy data-add-to-cart-price="false" data-default-to-first-variant="true">
    <div data-js-quick-buy-product-price="" id="product-price-quick_buy_wzzgtQ-template--18299834826913__featured_collection_new_RkNkxr-1" style="display:none">
     <div class="product-price">
      <span class="product-price--original pps" data-js-product-price-original="">
       ₹ 278
      </span>
      <del class="product-price--compare" data-js-product-price-compare="">
       <span>
        ₹ 299
       </span>
      </del>
      <span class="product-price--unit pps text-size--regular" data-js-product-price-unit="">
      </span>
     </div>
    </div>
    <product-variants class="product-variants--hide-unavailable product-variants--radio" data-has-variants="" data-hide-variants="hide" data-id="quick_buy_wzzgtQ-template--18299834826913__featured_collection_new_RkNkxr-1" data-no-history="" data-style="select" data-url="/products/salicylic-lha-2-cleanser" data-variants="1">
     <div class="product-variants no-js-hidden">
      <div class="product-variant" data-js-product-variant="" data-name="product-size-quick_buy_wzzgtQ-template--18299834826913__featured_collection_new_RkNkxr-1">
       <span class="product-variant__name text-size--small">
        Select Size
       </span>
       <div class="product-variant__container product-variant__container--radio" data-js-product-variant-container="radio">
        <div class="product-variant__item product-variant__item--radio" onclick="var r=this.querySelector('input[type=radio]');if(!r.checked){r.closest('product-variants').querySelectorAll('input[type=radio][checked]').forEach(e=&gt;e.removeAttribute('checked'));r.checked=true;r.closest('product-variants').dispatchEvent(new Event('change',{bubbles:true}))}">
         <input checked="" class="product-variant__input product-variant-value" id="quick-buy-salicylic-lha-2-cleanser-option-size-1-quick_buy_wzzgtQ-template--18299834826913__featured_collection_new_RkNkxr-1" name="quick-buy-size-quick_buy_wzzgtQ-template--18299834826913__featured_collection_new_RkNkxr-1" onchange="this.closest('product-variants').dispatchEvent(new Event('change',{bubbles:true}))" type="radio" value="100ml"/>
         <label class="product-variant__label text-size--small" for="quick-buy-salicylic-lha-2-cleanser-option-size-1-quick_buy_wzzgtQ-template--18299834826913__featured_collection_new_RkNkxr-1">
          100ml
         </label>
        </div>
        <div class="product-variant__item product-variant__item--radio" onclick="var r=this.querySelector('input[type=radio]');if(!r.checked){r.closest('product-variants').querySelectorAll('input[type=radio][checked]').forEach(e=&gt;e.removeAttribute('checked'));r.checked=true;r.closest('product-variants').dispatchEvent(new Event('change',{bubbles:true}))}">
         <input class="product-variant__input product-variant-value" id="quick-buy-salicylic-lha-2-cleanser-option-size-2-quick_buy_wzzgtQ-template--18299834826913__featured_collection_new_RkNkxr-1" name="quick-buy-size-quick_buy_wzzgtQ-template--18299834826913__featured_collection_new_RkNkxr-1" onchange="this.closest('product-variants').dispatchEvent(new Event('change',{bubbles:true}))" type="radio" value="250ml"/>
         <label class="product-variant__label text-size--small" for="quick-buy-salicylic-lha-2-cleanser-option-size-2-quick_buy_wzzgtQ-template--18299834826913__featured_collection_new_RkNkxr-1">
          250ml
         </label>
        </div>
       </div>
       <label for="product-size-quick_buy_wzzgtQ-template--18299834826913__featured_collection_new_RkNkxr-1" style="display: none;">
        Select Size
       </label>

In [11]:
products = soup.find_all("div", class_="product-item")

print("Total Products:", len(products))

Total Products: 12

In [12]:
from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()

driver.get("https://beminimalist.co/")

products = driver.find_elements(By.CLASS_NAME, "product-item")

for product in products:
    print(product.text)

driver.quit()

10ml
Salicylic Acid + LHA 2% Cleanser
Acne, Breakouts & Oiliness
4.2 out 5 stars rating in total {{reviews_count}} reviews
₹ 278 ₹ 299
100ml
250ml
Add to cart
Best Seller
SPF 50 Sunscreen
Sun protection, UV exposure / damage
3.9 out 5 stars rating in total {{reviews_count}} reviews
₹ 371 ₹ 399
50g
100g
Add to cart
Best Seller
Vitamin B5 10% Moisturizer
Damaged Barrier, Oily & Dehydrated
4.1 out 5 stars rating in total {{reviews_count}} reviews
₹ 325 ₹ 349
50g
100g
Add to cart
Best Seller
Niacinamide 10% Face Serum
Acne Marks, Acne Prone & Oily Skin
4 out 5 stars rating in total {{reviews_count}} reviews
₹ 557 ₹ 599
30ml
60ml
10ml
Add to cart
Best Seller












Hydrating Factors 7.3% Hair Shampoo
Manage dry, dull & frizzy hair
2.8 out 5 stars rating in total {{reviews_count}} reviews
₹ 464 ₹ 499
Add to Cart
New Launch
Multi Repair Actives 15% Face Serum
Dullness, Finelines & Loss of Firmness
3.4 out 5 stars rating in total {{reviews_count}} reviews
₹ 650 ₹ 699
Add to Cart
Marula Oil 05% Cleansing Oil
Gently remove oils and impurities
3.9 out 5 stars rating in total {{reviews_count}} reviews
₹ 557 ₹ 599
Add to Cart
Copper Peptide + PDRN 1.25% Face Serum
Wrinkles, Fine Lines, Damaged Barrier
3.8 out 5 stars rating in total {{reviews_count}} reviews
₹ 650 ₹ 699
Add to Cart

### Data Cleaning pipline
Data Cleaning (also called Data Cleansing or Data Wrangling) is the process of identifying and correcting errors, inconsistencies, duplicates, missing values, incorrect formats, and noisy data before analysis or machine learning.

concepts to learn:
- Basic Inspection
- Detect Missing Values (missing values appear as - NaN, None, Blank, NULL, ?, N/A, Unknown)
- Remove Missing Values
- Fill Missing Values
- Duplicate Data
- Incorrect Data Types
- Rename Columns
- Text Cleaning
- Handle Inconsistent Values
- Date Cleaning
- Outlier Detection and Removal
- Handle Categorical Variables

In [14]:
import pandas as pd
import numpy as np

In [18]:
df = pd.read_csv("Datasets/old_car_price_dataset.csv")
df

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.0,7.88 Lakh,4.75
6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.4 kmpl,1120 CC,71 bhp,5.0,NaN,4.00
6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.0 kmpl,2498 CC,112 bhp,8.0,NaN,2.90
6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.9 kmpl,998 CC,67.1 bhp,5.0,NaN,2.65
6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44 kmpl,936 CC,57.6 bhp,5.0,NaN,2.50

In [27]:
df.describe()

              Year  Kilometers_Driven        Seats        Price
count  6019.000000       6.019000e+03  5977.000000  6019.000000
mean   2013.358199       5.873838e+04     5.278735     9.479468
std       3.269742       9.126884e+04     0.808840    11.187917
min    1998.000000       1.710000e+02     0.000000     0.440000
25%    2011.000000       3.400000e+04     5.000000     3.500000
50%    2014.000000       5.300000e+04     5.000000     5.640000
75%    2016.000000       7.300000e+04     5.000000     9.950000
max    2019.000000       6.500000e+06    10.000000   160.000000

In [ ]:
# Basic Inspection

df.head()   # to view top 10 row in the dataframe

df.tail()   # to view bottom 10 row in the dataframe

df.sample(5) # it provide the random rows in the dataset

df.shape    # to know the dataframe size (no.of rows, no.of columns)

df.columns  # it give's only the dataset column names

df.info()   # it provide the dataset insight like (total rows, column names, no of non-null values, data-types)

df.describe() # it give the statistical score of numberical columns

df.dtypes  # it show the data-types

df.reset_index(drop=True)  # it reset the index of the dataset

In [ ]:
# Detect Missing Values

df.isnull()

df.isnull().sum()

df.isna().sum()

missing_percentage = (df.isnull().sum()/len(df))*100  # it give the missing values percentage %

# Remove Missing Values

df.dropna() # Remove rows

df.dropna(axis=1) # Remove columns

df.dropna(how='all') # Remove if all missing

In [ ]:
# Fill Missing Values

# Constant
df.fillna(0)

df.fillna("Unknown")

# Mean
df["Age"].fillna(df["Age"].mean())

# Median
df["Age"].fillna(df["Age"].median())

# Mode
df["City"].fillna(df["City"].mode()[0])

# Forward Fill
df.fillna(method="ffill")

# Backward Fill
df.fillna(method="bfill")

# Interpolation
df.interpolate(method="linear") # it use different methods (linear, polynomial, time, index, spline)

# Machine Learning Imputation
from sklearn.impute import SimpleImputer
# 
imputer = SimpleImputer(strategy="mean")  # here we can sue different strategy (mean, median, most_frequent, constan)
df["Age"] = imputer.fit_transform(df[["Age"]])

# The True ML Imuputation method 
""" 
KNNImputer: Fills missing values using the values of similar records (nearest neighbors).
IterativeImputer: Predicts missing values by repeatedly training regression models using the other features in the dataset.
"""

In [ ]:
# Duplicate Data

# Detect duplicates
df.duplicated()

df.duplicated().sum() # it give's total duplicate values count

# Remove duplicates
df.drop_duplicates()

# Based on columns
df.drop_duplicates(subset=["Email"])

In [ ]:
# Incorrect Data Types

# Check
df.dtypes

# Convert
df["Age"] = df["Age"].astype(int)

df["Salary"] = df["Salary"].astype(float)

df["Date"] = pd.to_datetime(df["Date"])

df["Category"] = df["Category"].astype("category")

In [ ]:
# Rename Columns
df.rename(columns={"Emp Name":"Employee_Name"})

# Lowercase
df.columns = df.columns.str.lower()

# Remove spaces
df.columns = df.columns.str.strip()

# Replace spaces
df.columns = df.columns.str.replace(" ","_")

In [ ]:
# Text Cleaning

# Lowercase
df["Name"] = df["Name"].str.lower()

# Uppercase
df["City"] = df["City"].str.upper()

# Title Case
df["Name"] = df["Name"].str.title()

# Remove spaces
df["Name"] = df["Name"].str.strip()

# Replace text
df["Gender"] = df["Gender"].replace("M","Male")

# Regular Expressions
import re

df["Phone"] = df["Phone"].str.replace(r"\D","",regex=True) 

# Remove special characters and digits
df["Name"] = df["Name"].str.replace(r"[^a-zA-Z0-9\s]","",regex=True)

# Remove special characters 
df["Name"] = df["Name"].str.replace(r"[^a-zA-Z\s]","",regex=True)

# remove blank spaces
df["Name"] = df["Name"].str.replace(r"\s+"," ",regex=True) # or

import numpy as np
df.replace("",np.nan,inplace=True) # it replace the blank spaces with NaN values

In [ ]:
# Handle Inconsistent Values
# Example
"""
Male
male
M
MALE
"""

# Standardize

df["Gender"] = df["Gender"].replace({
    "M":"Male",
    "male":"Male",
    "MALE":"Male"
})

In [ ]:
# Date Cleaning

# different format
df["Date"] = pd.to_datetime(df["Date"], format="%d-%m-%y")

# Extract
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day

In [ ]:
# Outlier Detection and Removal

# IQR Method

Q1 = df["salary"].quantile(0.25)
Q3 = df["salary"].quantile(0.75)
IQR = Q3-Q1

lower = Q1 - 1.5*IQR
upper = Q3 + 1.5*IQR

df = df[(df["salary"]>= lower) & (df["salary"] <= upper)]

# Z-Score Method

from scipy.stats import zscore

df["z_score"] = zscore(df["salary"])
df = df[(df["z_score"] >= -3) & (df["z_score"] <= 3)]

In [ ]:
# Handle Categorical Variables
df['column_name'].unique() # to get unique values of a specific column

df.nunique() # it provide the unique values count in the dataset

### EXPLORATORY DATA ANALYSIS (EDA)
Exploratory Data Analysis (EDA) is the process of exploring, summarizing, and visualizing data to understand its characteristics, identify patterns, detect anomalies, and discover relationships between variables before feature engineering or model building.

concepts to learn:
- Statistical Summary
- Univariate Analysis
- Bivariate Analysis
- Multivariate Analysis
- Outlier Analysis
- Correlation Analysis & Feature Relationships
- Distribution Analysis
- Group Analysis

In [ ]:
# Statistical Summary
df.describe()
df.describe(include='object')

In [ ]:
# Univariate Analysis - Study one variable at a time.
import matplotlib.pyplot as plt

plt.hist(df["Age"]) # histogram
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()

plt.boxplot(df["Age"]) # boxplot for outliers detection
plt.show()

"""Categorical Features
Questions:
Most common category?
Least common?
Class imbalance? """

df["Gender"].value_counts()

# Percentage

df["Gender"].value_counts(normalize=True)*100

# Bar Chart

df["Gender"].value_counts().plot(kind="bar")
plt.show()

In [ ]:
# Bivariate Analysis - Analyze two variables to understand their relationship.

# Numerical vs Numerical

# scatter plot to visualize the relationship between Age and Salary
plt.scatter(df["Age"], df["Salary"]) 
plt.xlabel("Age")
plt.ylabel("Salary")
plt.show()

# Numerical vs Categorical

df.boxplot(column="Salary", by="Department")
plt.show()

# Categorical vs Categorical

pd.crosstab(df["Gender"], df["Purchased"]) # cross tabulation to analyze the relationship
pd.crosstab(df["Gender"], df["Purchased"], normalize="index") # percentage distribution

In [ ]:
# Multivariate Analysis - Analyze more than two variables simultaneously.

pd.pivot_table(df,
               values="Sales",
               index="Region",
               columns="Category",
               aggfunc="mean")

In [ ]:
# Outlier Analysis

plt.boxplot(df["Salary"])
plt.show()

In [ ]:
# Correlation Analysis

corr = df.corr(numeric_only=True)

plt.imshow(corr)
plt.colorbar()
plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
plt.yticks(range(len(corr.columns)), corr.columns)
plt.show()

# Feature Relationships with Target Variable

df.corr(numeric_only=True)["Salary"].sort_values(ascending=False)

In [ ]:
# Distribution Analysis

df["Salary"].skew() # it check the skewness of the Salary column

In [ ]:
# Group Analysis

df.groupby("Department")["Salary"].mean()

# Multiple Aggregations

df.groupby("Department").agg({
    "Salary":["mean","max","min"],
    "Age":["mean","median"]
})

### Feature Engineering
Feature Engineering is the process of creating, transforming, selecting, and optimizing features (columns) so that machine learning algorithms can learn patterns more effectively.

concepts to learn:
- Feature Creation
- Feature Transformation
- Categorical Encoding
- Feature Scaling
- Date Feature Engineering
- Text Feature Engineering & Numerical Feature Binning
- Interaction Features & Cyclical Features & Missing value Indicators
- Aggregation Features

In [ ]:
# Feature Engineering - Create new columns from existing columns.

df["Total_Sales"] = df["Online"] + df["Offline"]

df["Age_Group"] = pd.cut(
    df["Age"],
    bins=[0,18,35,60,100],
    labels=["Child","Young","Adult","Senior"]
)

In [ ]:
# Feature Transformation - Transform skewed data.
# Log Transformation - Used for highly skewed data.

# Before Transformation - {"salary":[1000, 2000, 3000, 4000, 5000, 100000]}
df["Salary_Log"] = np.log1p(df["Salary"])

# Square Root Transformation - Used for moderately skewed data.
df["Salary_Sqrt"] = np.sqrt(df["Salary"])

# Power Transformation - Used for moderately skewed data.
from sklearn.preprocessing import PowerTransformer
pt = PowerTransformer()
df["Salary_Power"] = pt.fit_transform(df[["Salary"]])

In [ ]:
# Categorical Encoding - It use to convert categorical variables into numerical format.
# Because Machine learning models cannot directly use text values.

# Ordinal Encoding
mapping = {
    "Low":1,
    "Medium":2,
    "High":3
}

df["Priority"] = df["Priority"].map(mapping)

# Label Encoding - Assigns a unique integer to each category.
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["Gender"] = le.fit_transform(df["Gender"])

# one-hot Encoding - Creates binary columns for each category.
df = pd.get_dummies(df, columns=["Department"], drop_first=True) # with pandas get_dummies function 

# using sckit-learn OneHotEncoder
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(drop="first", sparse=False)
encoded_data = encoder.fit_transform(df[["Department"]])

In [ ]:
# Feature Scaling - Many algorithms require features to be on similar scales.

# Standardization - It rescales the data to have a mean of 0 and a standard deviation of 1.
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df[["Age","Salary"]] = scaler.fit_transform(df[["Age","Salary"]])

# Min-Max Scaling - It rescales the data to a fixed range of 0 to 1.
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df[["Age","Salary"]] = scaler.fit_transform(df[["Age","Salary"]])

# Robust Scaling - It uses the median and interquartile range to scale the data, making it robust to outliers.
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
df[["Age","Salary"]] = scaler.fit_transform(df[["Age","Salary"]])

In [ ]:
# Date Feature Engineering & Text Feature Engineering & Numerical Feature Binning

# Date Feature Engineering 

df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day
df["Weekday"] = df["Date"].dt.weekday
df["Quarter"] = df["Date"].dt.quarter
# Days Since
df["Days_Since"] = (
    pd.Timestamp.today()
    - df["Date"]
).dt.days

# Text Feature Engineering

df["Length"] = df["Review"].str.len() # length
# word count
df["Word_Count"] = (
    df["Review"]
    .str.split()
    .str.len()
)
# character count
df["Character_Count"] = (
    df["Review"].str.len()
)
# TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
X = tfidf.fit_transform(df["Review"])
# Bag of Words 
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(df["Review"])

# Numerical Feature Binning

pd.cut(df["Age"], bins=5)
pd.qcut(df["Salary"], q=4) # quantile binning

In [ ]:
# Interaction Features & Cyclical Features & Missing Value Indicators

# Interaction Features

df["Income_Per_Age"] = (df["Salary"] / df["Age"]) # multiple
# Polynomial Features
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2)
X_poly = poly.fit_transform(df[["Age","Salary"]])

# Cyclical Features 
"""Months repeat every year, weekdays every week, hours every day. 
Instead of treating them as simple numbers, encode them using sine and cosine."""
import numpy as np

df["Month_Sin"] = np.sin(2 * np.pi * df["Month"] / 12)
df["Month_Cos"] = np.cos(2 * np.pi * df["Month"] / 12)

# Missing Value Indicators - Sometimes the fact that a value is missing is informative.

df["Age_Missing"] = df["Age"].isna().astype(int)

In [ ]:
# Aggregation Features
"""
Customer Order Dataset:

Customer | Order Amount
    A    |      100
    A	 |      250
    A	 |      150 
"""

# Create customer statistics:

customer_avg = df.groupby("Customer")["OrderAmount"].transform("mean")
df["Customer_Avg_Order"] = customer_avg

"""
Other useful aggregations:

Mean
Median
Count
Max
Min
Sum
Standard deviation
"""

### Feature Selection
Feature Selection is the process of selecting the most relevant input variables (features) for training a machine learning model while removing irrelevant, redundant, or noisy features.

Types of Feature Selection:
| Type             | Description                             |
| ---------------- | --------------------------------------- |
| Filter Methods   | Statistics-based selection              |
| Wrapper Methods  | Model evaluates feature subsets         |
| Embedded Methods | Feature selection during model training |

concepts to learn:
- Dimensionality Reduction
- Filter Methods
- Wrapper Methods
- Embedded Methods
- Feature Importance Visualization

In [ ]:
# Dimensionality Reduction
"""
When there are too many features, reduce them while preserving information.

Common techniques:

  Technique   |       Use Case
PCA	Linear    |   dimensionality reduction
Truncated SVD |	  Sparse text data
Autoencoders  |	  Deep learning feature compression
"""

from sklearn.decomposition import PCA

pca = PCA(n_components=5)
X_reduced = pca.fit_transform(X)

In [ ]:
# Filter Methods- Filter methods evaluate each feature independently before model training.

# A. Remove Constant Features - A constant feature has the same value in every row.

from sklearn.feature_selection import VarianceThreshold
selector = VarianceThreshold(threshold=0)
X_new = selector.fit_transform(X)

# B. Remove Low Variance Features - Features with very little variation contribute little to learning.

selector = VarianceThreshold(threshold=0.01)
X_new = selector.fit_transform(X)

# C. Correlation-Based Selection - Highly correlated features contain similar information.
#Remove one feature if (Correlation > 0.90)

corr_matrix = df.corr(numeric_only=True).abs()
upper = corr_matrix.where(
    np.triu(np.ones(corr_matrix.shape), k=1).astype(bool)
)
to_drop = [
    column
    for column in upper.columns
    if any(upper[column] > 0.9)
]
df.drop(columns=to_drop, inplace=True)

# D. Chi-Square Test
"""
Used for: Classification

Requirements:
Categorical features or non-negative numeric features
Categorical target """
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
selector = SelectKBest(
    score_func=chi2,
    k=5
)
X_new = selector.fit_transform(X, y)

# E. ANOVA F-Test

from sklearn.feature_selection import f_classif
selector = SelectKBest(
    score_func=f_classif,
    k=5
)
X_new = selector.fit_transform(X, y)

# F. Mutual Information - Measures any dependency (linear or non-linear).
# Classification
from sklearn.feature_selection import mutual_info_classif
scores = mutual_info_classif(X, y)
# Regression
from sklearn.feature_selection import mutual_info_regression
scores = mutual_info_regression(X, y)

In [ ]:
# Wrapper Methods - Wrapper methods train models repeatedly to find the best feature subset.

# Recursive Feature Elimination (RFE) - One of the most popular methods.
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression
model = LinearRegression()
selector = RFE(
    estimator=model,
    n_features_to_select=5
)
X_new = selector.fit_transform(X, y)
# Selected Features
selector.support_
# Ranking
selector.ranking_

In [ ]:
# Embedded Methods - Selection happens while the model is being trained.

# Lasso Regression (L1) - Lasso shrinks unimportant coefficients to exactly zero.
from sklearn.linear_model import Lasso
model = Lasso(alpha=0.1)
model.fit(X, y)
model.coef_

# Decision Tree Importance
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X, y)
model.feature_importances_

#Random Forest Feature Importance
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X, y)
importance = model.feature_importances_

# Sort
import pandas as pd
pd.Series(
    importance,
    index=X.columns
).sort_values(ascending=False)

# Gradient Boosting / XGBoost Feature Importance - Most boosting libraries provide feature importance after training.
importance = model.feature_importances_

"""
Multicollinearity:

When two or more features are highly correlated.

Example:

Height(cm)
Height(m)

Both provide the same information.

Problems
- Unstable coefficients
- Difficult interpretation
- Poor regression performance
"""

# Variance Inflation Factor (VIF)
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif = pd.DataFrame()
vif["Feature"] = X.columns
vif["VIF"] = [
    variance_inflation_factor(
        X.values,
        i
    )
    for i in range(X.shape[1])
]

# Sequential Feature Selector - Automatically performs forward or backward selection.
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
sfs = SequentialFeatureSelector(
    model,
    n_features_to_select=5,
    direction="forward"
)
X_new = sfs.fit_transform(X, y)

In [ ]:
# Feature Importance Visualization
importance = pd.Series(
    model.feature_importances_,
    index=X.columns
)

importance.sort_values().plot.barh()

#### Feature Selection for Different ML Problems

| Problem             | Recommended Methods                               |
| ------------------- | ------------------------------------------------- |
| Linear Regression   | Correlation, VIF, RFE, Lasso                      |
| Logistic Regression | Chi-Square, Mutual Information, L1 Regularization |
| Decision Tree       | Tree Importance                                   |
| Random Forest       | Feature Importance                                |
| XGBoost             | Gain, Weight, SHAP                                |
| Text Classification | Chi-Square, Mutual Information                    |
| Time Series         | Correlation, Lag Analysis, Tree Importance        |

### Data Splitting & Validation